version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      # این متغیرها مستقیماً در اینجا تعریف می شوند
      POSTGRES_DB: myshop
      POSTGRES_USER: myshop_user
      POSTGRES_PASSWORD: myshop_password # این رمز عبور نباید در گیت کامیت شود!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./backend
    container_name: django_web
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    # این بخش برای اطمینان از اینکه برنامه به دیتابیس وصل می شود
    # اگر settings.py از این متغیرها استفاده می کند
    environment:
      DB_NAME: myshop
      DB_USER: myshop_user
      DB_PASSWORD: myshop_password
      DB_HOST: db
      DB_PORT: 5432
    # همچنین اگر SECRET_KEY و DEBUG را از .env می خوانید، باید ان را نگه داریم
    env_file:
      - .env
    depends_on:
      - db
    
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

volumes:
  postgres_data:
