# Generated by Django 5.2.14 on 2026-09-28 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cartitem_quantity'),
        ('inventory', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant', to='inventory.productvariant', verbose_name='variant'),
        ),
    ]
