# Generated by Django 5.2.11 on 2026-02-15 17:33

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category/', verbose_name='image')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.variant_image_upload_path, verbose_name='image'),
        ),
    ]
