name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Verify file access
      run: |
        pwd
        ls -la
        find . -maxdepth 4 -name 'Dockerfile*' -print

    - name: Create .env file
      run: |
        touch .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "DEBUG=True" >> .env
    
    - name: Start services
      run: docker compose up -d

    # مرحله جدید: اجرای migration ها
    - name: Apply database migrations
      # نام سرویس 'web' فرض شده است. اگر فرق دارد، اصلاح کنید.
      # اطمینان حاصل کنید که secret های دیتابیس در .env اضافه شده اند اگر لازم است
      run: docker compose exec web sh -c 'python manage.py migrate --noinput'

    # اجرای تست ها
    - name: Run Tests
      # نام سرویس 'web' فرض شده است. اگر فرق دارد، اصلاح کنید.
      run: docker compose exec web sh -c 'pytest'

    - name: Stop services
      if: always()
      run: docker compose down
